// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication6.DynamicRouting.DataAccess;

#nullable disable

namespace WebApplication6.DynamicRouting.Migrations
{
    [DbContext(typeof(FolderContext))]
    [Migration("20221215031203_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication6.DynamicRouting.Models.VirtualFolder", b =>
                {
                    b.Property<int>("FolderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FolderId"));

                    b.Property<int?>("DepthLevel")
                        .HasColumnType("int");

                    b.Property<string>("FolderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("IdParentFolder")
                        .HasColumnType("int");

                    b.HasKey("FolderId");

                    b.HasIndex("FullPath")
                        .IsUnique();

                    b.HasIndex("IdParentFolder");

                    b.ToTable("Folders");

                    b.HasData(
                        new
                        {
                            FolderId = 1,
                            DepthLevel = 0,
                            FolderName = "Creating Digital Images",
                            FullPath = "Creating Digital Images"
                        },
                        new
                        {
                            FolderId = 2,
                            DepthLevel = 1,
                            FolderName = "Resources",
                            FullPath = "Creating Digital Images/Resources",
                            IdParentFolder = 1
                        },
                        new
                        {
                            FolderId = 6,
                            DepthLevel = 1,
                            FolderName = "Graphic Products",
                            FullPath = "Creating Digital Images/Graphic Products",
                            IdParentFolder = 1
                        },
                        new
                        {
                            FolderId = 3,
                            DepthLevel = 1,
                            FolderName = "Evidence",
                            FullPath = "Creating Digital Images/Evidence",
                            IdParentFolder = 1
                        },
                        new
                        {
                            FolderId = 7,
                            DepthLevel = 2,
                            FolderName = "Process",
                            FullPath = "Creating Digital Images/Graphic Products/Process",
                            IdParentFolder = 6
                        },
                        new
                        {
                            FolderId = 8,
                            DepthLevel = 2,
                            FolderName = "Final Product",
                            FullPath = "Creating Digital Images/Graphic Products/Final Product",
                            IdParentFolder = 6
                        },
                        new
                        {
                            FolderId = 4,
                            DepthLevel = 2,
                            FolderName = "Primary Sources",
                            FullPath = "Creating Digital Images/Resources/Primary Sources",
                            IdParentFolder = 2
                        },
                        new
                        {
                            FolderId = 5,
                            DepthLevel = 2,
                            FolderName = "Secondary Sources",
                            FullPath = "Creating Digital Images/Resources/Secondary Sources",
                            IdParentFolder = 2
                        });
                });

            modelBuilder.Entity("WebApplication6.DynamicRouting.Models.VirtualFolder", b =>
                {
                    b.HasOne("WebApplication6.DynamicRouting.Models.VirtualFolder", "ParentFolder")
                        .WithMany("Children")
                        .HasForeignKey("IdParentFolder");

                    b.Navigation("ParentFolder");
                });

            modelBuilder.Entity("WebApplication6.DynamicRouting.Models.VirtualFolder", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
